/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Entity.Track;
import Entity.Segment;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Yan
 */
public class VisualTrack extends javax.swing.JPanel {

  private final List<VisualSegment> segments;
  private boolean selection;

  /**
   *
   */
  public VisualTrack() {
    initComponents();
    segments = new ArrayList<>();
    Rectangle bounds = segmentsPanel.getBounds();
  }

  /**
   *
   * @param band
   */
  public void setBand(Track band) {
    this.titleLabel.setText(band.getName());
    Dimension size = getSize();
    size.width = (int) (band.getDuration().toMillis() / 100);
    this.setSize(size);    
    
    for(Segment seg : band.getSegments()){
      VisualSegment vseg = new VisualSegment(seg);
      segments.add(vseg);
      segmentsPanel.add(vseg);
    }
  }
  
  public void addSegment(VisualSegment segment){
    segments.add(segment);
    segmentsPanel.add(segment);
  }
  
  public boolean isSelected(){
    return selection;
  }
  
  public void select(){
    this.selection = true;
    setBackground(SystemColor.textHighlight);
  }
  
  public void unselect(){
    this.selection = false;
    setBackground(SystemColor.controlHighlight);
  }
  
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    segmentsPanel = new javax.swing.JPanel();
    titleLabel = new javax.swing.JLabel();

    setBackground(java.awt.SystemColor.controlHighlight);
    setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    setDoubleBuffered(false);

    segmentsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    segmentsPanel.setLayout(null);

    titleLabel.setBackground(java.awt.SystemColor.textHighlight);
    titleLabel.setText("Titulo da Faixa");
    titleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(segmentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(segmentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel segmentsPanel;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
