/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transcriber;

import Entity.Segment;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import view.VisualSegment;

/**
 * Tela principal do programa, feita em swing, com modulos feitos em JavaFX
 *
 * @author Yan Kaic
 * @author Carlos Hatus
 */
public class MainFrame extends javax.swing.JFrame {

    private Segment seg;
    private VisualSegment vseg;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    videoPanel1 = new transcriber.VideoPanel();
    timeline1 = new view.Timeline();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    newMenu = new javax.swing.JMenuItem();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setForeground(java.awt.Color.white);

    jMenu1.setText("Arquivo");

    newMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    newMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
    newMenu.setText("Novo");
    newMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newMenuActionPerformed(evt);
      }
    });
    jMenu1.add(newMenu);

    jMenuItem1.setText("Abrir Wav");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Editar");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Faixa");

    jMenuItem2.setText("adicionar faixa");
    jMenu3.add(jMenuItem2);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 487, Short.MAX_VALUE)
        .addComponent(videoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(timeline1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(videoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(timeline1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void newMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuActionPerformed
      //new FileSelectDialog(this, videoPanel1).setVisible(true);
      // mudancas para o cancelar funcionar 01/04/2015 Carlos
      JFileChooser selector = new JFileChooser();
      selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
      if (selector.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) {
          selector.removeAll();
      } else {
          String txt = selector.getSelectedFile().toURI().toString();
          videoPanel1.load(txt);
          System.out.println(txt);
      }
      //fim das mudancas
      pack();
      repaint();
  }//GEN-LAST:event_newMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//      JFileChooser selector = new JFileChooser();
//      selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
//      if (selector.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) {
//          selector.removeAll();
//      } else {
//          String txt = selector.getSelectedFile().toURI().toString();
//          File file = selector.getSelectedFile();
//          try {
//              AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new BufferedInputStream(new FileInputStream(file))); // cria um objeto AudioInputStream
//              waveformPanelContainer1.setAudioToDisplay(audioInputStream); // passa o AudioInputStream como parametro para o setAudioToDisplay de WaveformPanelContainer
//          } catch (MalformedURLException ex) {
//              ex.printStackTrace(System.out);
//          } catch (FileNotFoundException ex) {
//              ex.printStackTrace(System.out);
//          } catch (UnsupportedAudioFileException | IOException ex) {
//              ex.printStackTrace(System.out);
//          }
//          videoPanel1.load(txt);
//          System.out.println(txt);
//      }
//      //fim das mudancas
//      pack();
//      repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Metodo principal da classe que torna a janela do programa visivel
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        new MainFrame().setVisible(true);

    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem newMenu;
  private view.Timeline timeline1;
  private transcriber.VideoPanel videoPanel1;
  // End of variables declaration//GEN-END:variables
}
